#!/bin/bash
set -e
source "$HOME/.bashrc"
command -v pyenv || (echo "need pyenv installed" && exit 1)
for version in $@; do
  pyenv install "$version"
  pyenv shell "$version"
  pip install ".[all, testing]"
done
