#!/bin/bash
set -e

python_version=${1:-3.6.14}
docker_registry=${2-""}

script_dir="$(realpath $(dirname $0))"
source "$script_dir/util-lib.sh"
skip_if_no_changed_file_match "^(preview_generator|tests|concourse|setup.py|setup.cfg|pytest.ini)"

source "$HOME/.bashrc"
pyenv shell "$python_version"

pip install ".[all, testing]"

# Configuration to get most builder working
GLTF_EXPERIMENTAL_SUPPORT_ENABLED=1
rm -f /etc/ImageMagick-6/policy.xml
export DISPLAY=:99.0
which Xvfb
Xvfb :99 -screen 0 1x1x16 > /dev/null 2>&1 &

pytest tests
