blank_issues_enabled: false
contact_links:
  - name: Using  Windows/MacOSX/Non-Debian Linux Distrib ?
    url: https://github.com/algoo/preview-generator/issues/241
    about: Metaticket about support for non-debian/ubuntu distrib.
